name: pygbag_build
on: [workflow_dispatch]

jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pygbag and Build
      run: |
        python -m pip install pygbag
        python -m pygbag --build $GITHUB_WORKSPACE/robot/main.py
    - name: Upload to GitHub Pages branch gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: robot/build/web




        
